Задание 1.2.1

In [2]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


Задание 1.2.2

In [5]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


Задание 1.2.3

In [6]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.01052441784632574 0.9971649474237385 0.5108352465503976


Задание 1.2.4

In [8]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Задание 1.2.5

In [9]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


Задание 1.2.6

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


Задание 1.3.1

In [3]:
arr = np.full(64, 0).reshape(8, 8)
for i in range(8):
    if i % 2 == 0:
        arr[i][1:8:2] = 1
    else:
        arr[i][0:8:2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 1.3.2

In [4]:
arr = np.arange(25).reshape(5, 5)
for i in range(1, 5):
    arr[i] = arr[0]

print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


Задание 1.3.3

In [5]:
import numpy as np
rand = np.random.random((3,3,3))
print(rand)

[[[0.1020879  0.78579672 0.04299592]
  [0.91707922 0.97222483 0.99677421]
  [0.60293366 0.63917193 0.11223005]]

 [[0.52465768 0.44414673 0.7444327 ]
  [0.09824069 0.70788424 0.74066599]
  [0.09042387 0.2805503  0.56008752]]

 [[0.16249732 0.34336907 0.86401741]
  [0.071877   0.32742422 0.06289253]
  [0.97889726 0.58381394 0.12603034]]]


Задание 1.3.4

In [6]:
size = 7
arr = np.full(size*size, 0).reshape(size, size)

for i in range(size):
    if i == 0 or i == size-1:
        arr[i] = np.full(size, 1)
        continue
    arr[i][0], arr[i][size-1] = 1, 1

print(arr)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


Задание 1.3.5

In [24]:
arr = np.random.random(10)
print(np.sort(arr)[::-1])

[0.99830774 0.87850381 0.81497412 0.63614717 0.63305421 0.51269698
 0.24673408 0.12700107 0.11761941 0.09688456]


Задание 1.3.6

In [26]:
arr = np.random.random((3, 3, 3))
print(arr.shape)

(3, 3, 3)


Задание 2.2.1

In [9]:
import pandas as pd

lst = [1, 2, 3, 4, 5]
d = {'a':1,'b':2,'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr)

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int32


Задание 2.2.2

In [10]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a','b','c','d','e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


Задание 2.2.3

In [11]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

Задание 2.2.4

In [12]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

Задание 2.2.5

In [13]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

Задание 2.2.6

In [14]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

Задание 2.2.7

In [15]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

Задание 2.3.1

In [16]:
a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([5, 4, 3, 2, 1])
print(sum((a-b)**2)**0.5)

6.324555320336759


Задание 2.3.2

In [35]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/australian.csv'

dataframe = pd.read_csv(url)
dataframe.head(5)
dataframe

A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
0     1   65  168   2   4   4  39   0   0    1    1    2   32  161          0
1     0   72  123   2   8   4   5   0   0    1    0    2   53    1          0
2     0  142   52   1   4   4  31   0   0    1    1    2   98    1          0
3     0   60  169   1   5   3   1   1   1   12    1    2    1    1          1
4     1   44  134   2   6   4  46   1   1   15    0    2   18   68          1
..   ..  ...  ...  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...        ...
685   1  163  160   2  14   4  99   1   0    1    0    2    1    1          1
686   1   49   14   2   8   4   4   0   0    1    0    2    1   35          0
687   0   32  145   2   6   4   3   1   0    1    0    2   32    1          1
688   0  122  193   2  14   8  67   1   1    2    0    2   38   12          1
689   1  245    2   2  10   4   2   0   1    2    0    1  159    1          1

[690 rows x 15 columns]

Задание 2.3.3

In [42]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['A1'] == 1].head(2)


A1  A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
0   1  65  168   2   4   4  39   0   0    1    1    2   32  161          0
4   1  44  134   2   6   4  46   1   1   15    0    2   18   68          1

Задание 3.2.1

In [20]:
import sklearn.preprocessing as preproc

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preproc.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

Задание 3.2.2

In [21]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preproc.StandardScaler()
standardized = scaler.fit_transform(x)

print(standardized)
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее: 0
Стандартное отклонение: 1.0


Задание 3.2.3

In [22]:
scaler = preproc.MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                           'B':[103.02,107.26,110.35,114.23,114.68],
                           'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

Задание 3.3.2

In [43]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe = pd.read_csv(url)
scale1 = preproc.MinMaxScaler()
scale2 = preproc.StandardScaler()
dataframe[['sepal_length_cm']] = scale1.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = scale2.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]